#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1091

source /scripts/common

# Start telegraf if required
if [[ -n "$INFLUXDBV2_URL" ]] || chk_enabled "${PROMETHEUS_ENABLE}"; then
    # start telegraf
    telegraf --config-directory /etc/telegraf/telegraf.d 2>&1
else
    # if telegraf not needed, sleep forever
    sleep infinity
fi
